name: PSI Fetch

on:
  workflow_dispatch:
    inputs:
      urls:
        description: 'Space separated URLs (override pages.json)'
        required: false
        default: ''
      locale:
        description: 'Locale for PSI (zh_CN, zh_TW, en)'
        required: false
        default: 'zh_CN'
      strategy:
        description: 'PSI strategy (mobile, desktop, both)'
        required: false
        default: 'both'
      fail_on_error:
        description: 'Fail job if all requests fail (true/false)'
        required: false
        default: 'false'
  schedule:
    - cron: '0 3 * * *'  # 每天 03:00 UTC 运行
  push:
    branches:
      - main

jobs:
  run-psi:
    runs-on: ubuntu-latest
    env:
      PSI_API_KEY: ${{ secrets.PSI_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --prefer-offline --no-audit --no-fund

      - name: Ensure deliverables directory
        run: |
          mkdir -p "交付物"

      - name: Resolve URLs from pages.json
        id: urls
        shell: bash
        run: |
          if [ -n "${{ github.event.inputs.urls }}" ]; then
            echo "urls=${{ github.event.inputs.urls }}" >> $GITHUB_OUTPUT
          else
            if [ -f "交付物/pages.json" ]; then
              URLS=$(node -e "const fs=require('fs');const j=JSON.parse(fs.readFileSync('交付物/pages.json','utf8'));console.log((j.urls||[]).join(' '))")
              echo "urls=${URLS}" >> $GITHUB_OUTPUT
            else
              echo "urls=https://wishesvideo.com/ https://wishesvideo.com/collections/all" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Network diagnostics to PSI API and site
        shell: bash
        run: |
          set -e
          for U in \
            "https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url=https://wishesvideo.com/&strategy=mobile" \
            "https://wishesvideo.com/"; do
            echo ">>> $U"
            curl -sS -o /dev/null -w "lookup:%{time_namelookup}\nconnect:%{time_connect}\nappconnect:%{time_appconnect}\nstarttransfer:%{time_starttransfer}\ntotal:%{time_total}\n" "$U" || true
          done

      - name: Run PSI
        shell: bash
        run: |
          STRATEGY="${{ github.event.inputs.strategy }}"
          LOCALE="${{ github.event.inputs.locale }}"
          FAIL="${{ github.event.inputs.fail_on_error }}"
          if [ -z "$STRATEGY" ]; then STRATEGY="both"; fi
          if [ -z "$LOCALE" ]; then LOCALE="zh_CN"; fi
          if [ -z "$FAIL" ]; then FAIL="false"; fi
          EXTRA="--fail-on-error $FAIL"

          if [ -n "$PSI_API_KEY" ]; then
            echo "Using PSI API key"
            node fetch-psi-report.js ${{ steps.urls.outputs.urls }} --strategy "$STRATEGY" --locale "$LOCALE" --key "$PSI_API_KEY" $EXTRA
          else
            echo "No PSI API key; running without key"
            node fetch-psi-report.js ${{ steps.urls.outputs.urls }} --strategy "$STRATEGY" --locale "$LOCALE" $EXTRA
          fi

      - name: Upload deliverables
        uses: actions/upload-artifact@v4
        with:
          name: psi-deliverables
          path: |
            交付物/性能报告.md
            交付物/psi-results.json
            交付物/优化建议.md